### ISSUE TITLE
Breaks on Linux with Node v14 due to fs changes

### ISSUE THREAD

**Issue by taylorlapeyre** [rsms/serve-http#6]
Error:

```
app_1    | Unhandled exception: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
app_1    |     at Object.fs [as watch] (fs.js:1578:11)
app_1    |     at zb.watch (/app/node_modules/serve-http/src/livereload.js:158:20)
app_1    |     at nb.<anonymous> (/app/node_modules/serve-http/src/server.js:139:7)
app_1    |     at Object.onceWrapper (events.js:481:28)
app_1    |     at nb.emit (events.js:375:28)
app_1    |     at Server.emit (events.js:375:28)
app_1    |     at emitListeningNT (net.js:1354:10)
app_1    |     at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Node v14 introduced a breaking change to the fs.watch() API, specifically that the recursive option (which has never been supported on Linux) now raises the ERR_FEATURE_UNAVAILABLE_ON_PLATFORM error if used on Linux. Looks like there will need to be some other way to watch files recursively!

Actually fairly important to fix if anyone is interested in using this tool with docker (as I'm experimenting with)

**Comment by drewhutchison** [comment]
This is root cause of https://github.com/penrose/penrose/issues/565.

@rsms, would it be possible to either 1) merge the above PR or 2) implement something similar with chokidar, along the lines of https://github.com/rsms/estrella/commit/5b894fd9c16d7cc0cb587627312e5fbf9ccddb49 ?

If you prefer (2) and don't have time I'm happy to implement but wanted to check with you first.
